# Generated by Django 4.2 on 2023-04-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contact_message_alter_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='onlysocial_images')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
    ]
